local title = {}
require('mh.table')

function address(res)
		local lines={}

		local s=res.street		
		if 0<#res.postal then s=s.." "..res.postal end
		if 0<#res.city then s=s.." "..res.city end
		if 0<#res.country then s=s.." "..res.country end
		
		if 0<#s then table.insert(lines,"adres: "..s) end
		if 0<#res.email then table.insert(lines,"email: "..res.email) end
		if 0<#res.phone then table.insert(lines,"phone: "..res.phone) end
 
		return table.concat(lines,", ")
end

title.author = function()return gramps6.researcher().name end
title.address= function()return address(gramps6.researcher()) end

title.input = function()
	local title = "Familie van "..gramps6.Person(gramps_id):fullname()..
		"\\footnote{Generated by grpsLuaLaTeX by M.Heijn  from sqlite database Gramps}"

	print("\\author{"..title.author().."}")
	print("\\title{"..title.."}")

end
		
return(title)
